POST http://127.0.0.1:4880/math/add HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "name1": "sample",
    "time1": "Wed, 21 Oct 2015 18:27:50 GMT",
    "name2": "sample",
    "time2": "Wed, 21 Oct 2015 18:27:50 GMT",
    "name3": "sample",
    "time3": "Wed, 21 Oct 2015 18:27:50 GMT",
    "name4": "sample",
    "time4": "Wed, 21 Oct 2015 18:27:50 GMT"
}